### ISSUE TITLE
updateJob 'passed' field value is not correct

### ISSUE THREAD

**Issue by TarCV** [saucelabs-sample-test-frameworks/JS-Nightwatch.js#12]
Example code in customSauceEnd leads to false negatives in SauceLabs dashboard. `currentTest.results.failed` is the number of failures in the entire test suite (file). So after the first failed test case in a suite, following test cases are always displayed as failed.

To fix the problem I changed `passed` argument to `currentTest.results.testcases[currentTest.results.name].failed`.

My setup was similar to this one:
```
// test.js
testcase: function (browser) {
  //...
  browser.end();
}

after: function (browser, done) {
  browser.globals.afterEachTestcase(browser);
  done();
}

// globals.js
afterEachTestcase(browser) {
  //...
  saucelabs.updateJob(browser.capabilities['webdriver.remote.sessionid'], {
        passed: browser.currentTest.results.failed === 0,
        name: browser.currentTest.name
  }, function() {});
  //...
}
```

**Comment by ndmanvar** [comment]
Will look into this @TarCV !
Thank you for reporting and going over the fix.

**Comment by mehmetg** [comment]
@TarCV Would you care to make a PR?

**Comment by ndmanvar** [comment]
Should be fixed by https://github.com/saucelabs-sample-test-frameworks/JS-Nightwatch.js/pull/13

Let me know if you have any questions.
