### ISSUE TITLE
more recent example browser setup

### ISSUE THREAD

**Issue by peter-mouland** [saucelabs-sample-test-frameworks/JS-Nightwatch.js#8]
hey,

I'm struggling to find the correct setup for more recent browsers (e.g. xp is not supported)
windows 10/8 chrome, 53 etc.

Would it be possible to update the examples?

**Comment by KevinMarkVI** [comment]
You can choose any set of values from our platform configurator page to change the environment in which your tests will be executed. Link below:

https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/

You can change/create environments in the nightwatch.json file.

**Comment by peter-mouland** [comment]
i see. thanks
