### ISSUE TITLE
Browser version and Platform not taken into account

### ISSUE THREAD

**Issue by manodupont** [saucelabs-sample-test-frameworks/JS-Nightwatch.js#9]
I wasn't able to make the browser version and platform taken into account by saucelabs.

This is my config (Taken from this example, i reduced it a bit)

```
{
  "src_folders" : ["e2e/tests"],
  "output_folder" : "e2e/reports",
  "custom_commands_path" : "e2e/command",
  "custom_assertions_path" : "",
  "page_objects_path" : "",
  "globals_path" : "",


  "selenium" : {
    "start_process" : true,
    "server_path" : "",
    "log_path" : "",
    "host" : "127.0.0.1",
    "port" : 4444,
    "cli_args" : {
      "webdriver.chrome.driver" : "",
      "webdriver.ie.driver" : ""
    }
  },

  "test_workers" : {"enabled" : true, "workers" : "auto"},
  "test_settings" : {
    "default" : {
      "launch_url": "http://localhost",
      "selenium_port"  : 80,
      "selenium_host"  : "ondemand.saucelabs.com",
      "use_ssl" : false,
      "silent": true,
      "end_session_on_fail" : false,
      "screenshots" : {
        "enabled" : true,
        "path" : ""
      },
      "username" : "${SAUCE_LABS_USERNAME}",
      "access_key" : "${SAUCE_LABS_ACCESS_KEY}",

      "desiredCapabilities": {
        "javascriptEnabled": true,
        "acceptSslCerts": true
      }
    },

    "chrome": {
      "desiredCapabilities": {
        "platform": "Windows XP",
        "browserName": "chrome",
        "version": "41.0"
      }
    },

    "firefox" : {
      "desiredCapabilities": {
        "platform": "Windows XP",
        "browserName": "firefox",
        "version": "33.0"
      }
    }
  }
}
```

**Comment by ndmanvar** [comment]
@manodupont Taking a look at this and will get back to you. Appreciate you filing the issue and giving me your config file

**Comment by manodupont** [comment]
I think i found.

I need to specifically call them with -e switch in Nightwatch.

But i thought it was automatic though...

Sent from my iPhone

On Oct 25, 2016, at 16:05, Neil Manvar <notifications@github.com<mailto:notifications@github.com>> wrote:

@manoduponthttps://github.com/manodupont Taking a look at this and will get back to you. Appreciate you filing the issue and giving me your config file

##

**Comment by ndmanvar** [comment]
you need to use `-e` in order to use the environments (chrome, firefox, etc.)

closing this for now. feel free to reach out to me if you are having issues. would be more than happy to help via video call + screenshare
